### PR TITLE
Feat/faq

### PR DESCRIPTION
**Pull request by aliceoq**
#### What is the purpose of this pull request?

To add the FAQ pages.

#### What problem is this solving?

- Added page that lists FAQs
- Added page to show FAQ docs
- Fixed position of the 'reading time' text in tracks and known issues.
- Fixed filter/sort button height/padding
- Fixed FAQ routes in sidebar, menu and hamburger menu

#### How should this be manually tested?

Open the preview and check if all the problems mentioned above are solved. Be sure to check the known issues and tracks pages, check all breakpoints and test the filter in the [FAQ listing page](https://deploy-preview-30--leafy-mooncake-7c2e5e.netlify.app/pt/faq).

#### Screenshots or example usage

image

image

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by ThayllyR — APPROVED** [review]
Great job ✨ LGTM

**Review by Pvcunha — APPROVED** [review]
LGTM

**Review by ThayllyR — APPROVED** [review]
LGTM ✨

**Review by RobsonOlv — APPROVED** [review]
LGTM :rocket: :clap:

**Pull request merged**
