### PR TITLE
Feat/troubleshooting page

### PR DESCRIPTION
**Pull request by phvm**
#### What is the purpose of this pull request?

Create a page for troubleshooting articles

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by PedroAntunesCosta — CHANGES_REQUESTED** [review]
No content is loaded in any article or list page. I thought the problem could be in the `getDocsPaths` function. But it looks right.

> I created a test branch in the `help-center-content` repo, changing the folder structure to include the existing troubleshooting articles. You can use it to test the page: `troubleshooting-test`

Also, there should be a card in the `Documentation` section of the home page (next to 'start here', etc).

**Comment by phvm** [comment]
I think the problem was some other function which was updated some time ago. I'll rebase and test with the help-center-content branch

**Review by PedroAntunesCosta — CHANGES_REQUESTED** [review]
Great!

There is just one feat missing: content branch preview. It helps us test content changes.

See [L160-L165 of the faq page](https://github.com/vtexdocs/helpcenter/blob/main/src/pages/faq/index.tsx#L160).

**Comment by phvm** [comment]
Isn't already in [L148](https://github.com/vtexdocs/helpcenter/blob/1e74b409e86573d660969f93fd34f604b599b089/src/pages/troubleshooting/index.tsx#L148)?

**Comment by PedroAntunesCosta** [comment]
The way it is coded, the preview branch is being used to get content from the path, but it is not being used to get the paths. It becomes relevant if we change the folder structure or remove/add files.

In order for it to work, you have to move L146 to after the declaration of `branch` and then add it as a parameter of `getTroubleshootingPaths`:

```
const docsPathsGLOBAL = await getTroubleshootingPaths('troubleshooting', branch)
```

This is the way it is done in the example I sent above:

```
  const previewBranch =
    preview && JSON.parse(JSON.stringify(previewData)).hasOwnProperty('branch')
      ? JSON.parse(JSON.stringify(previewData)).branch
      : 'main'
  const branch = preview ? previewBranch : 'main'
  const docsPathsGLOBAL = await getFaqPaths('faq', branch)
```

**Comment by PedroAntunesCosta** [comment]
Currently, content branch preview is not working on this deploy. If you make this change, we will be able to see the page working properly by going to:

```
https://deploy-preview-99--leafy-mooncake-7c2e5e.netlify.app/api/preview?branch=troubleshooting-test
```

**Comment by phvm** [comment]
Just commited the needed changes!

**Pull request merged**
