### PR TITLE
Feat/cards page search

### PR DESCRIPTION
**Pull request by phvm**
#### What is the purpose of this pull request?

Create a search bar for pages with cards

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by PedroAntunesCosta — CHANGES_REQUESTED** [review]
The KI and FAQ searches are case sensitive. It would be best if they were case insensitive, like the search bar that already exists in the announcements page.

**Comment by phvm** [comment]
Implemented both changes

**Review by PedroAntunesCosta — APPROVED** [review]
LGTM

**Review by julia-rabello — APPROVED** [review]

**Review by PedroAntunesCosta — APPROVED** [review]
LGTM

**Pull request closed without merging**
