### PR TITLE
feat/localized slugs

### PR DESCRIPTION
**Pull request by julia-rabello**
#### What is the purpose of this pull request?

- updating navigation.json with localized slugs based on https://github.com/vtexdocs/help-center-content/pull/43
- delivering all types of content correctly when using localized slugs (tutorials, tracks, announcements, faqs, known issues)
- removing announcements from navigation.json, as they are not organized by this file, but by the AnnouncementSection component
- adding all content types (announcements, faqs, known issues besides tutorials and tracks) to navigation.json based on help-center-content files even if they're not used in the sidebar, so that navigation can serve as a map for localized slugs based on slugEN frontmatter property
- updating the locale switcher to identify localized slugs for tutorials, tracks, announcements, known issues, and faqs based on navigation.json
- adding all other content types (announcements, faqs, known issues) to navigation.json even if they're not used in the sidebar, so that navigation can serve as a map for localized slugs based on slugEN frontmatter property

>⚠️  relates to https://github.com/vtexdocs/components/pull/26 (updating the sidebar based on the new navigation.json structure). to test it with this sidebar feature, it is necessary to change L31 of package.json to:
> ```json
>     "@vtexdocs/components": "https://github.com/vtexdocs/components.git#feat/sidebar-localized-slugs",
> ```

#### How should this be manually tested?

1. run `yarn && yarn dev` with this branch checked out
2. go to http://localhost:3000/api/preview?branch=localized-slugs
3. visit pages with localized slugs (e.g. http://localhost:3000/pt/docs/tutorial/configurar-login-com-apple-id-beta / http://localhost:3000/es/docs/tutorial/configurar-inicio-de-sesion-con-apple-id-beta)

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by PedroAntunesCosta — CHANGES_REQUESTED** [review]
Great! I tested it and most of the features are working.

But I think I found a bug. I tried to change the locale from EN to PT in the first article of the Catalog track and the URL changed from
```
http://localhost:3000/docs/tracks/catalog-concept-definition
```

to
```
http://localhost:3000/pt/docs/catalog-concept-definition/undefined
```

And it returned `404`.

image

I think the cause may be that it was without locale. And it may have to do with the fact that I got to that article via the tracks page.

**Comment by PedroAntunesCosta** [comment]
I tested a similar path for:
- KIs: ✅ worked
- FAQs: ❌ same error 👇 
```
http://localhost:3000/es/the-price-in-the-search-result-is-different-from-the-product-page/undefined
```

Also, I couldn't access the announcements page:
image

**Comment by PedroAntunesCosta** [comment]
I just noticed the `/announcements` page works in EN, but returns the error above in ES and PT.

**Review by PedroAntunesCosta — CHANGES_REQUESTED** [review]
When I do the same test I reported above, the page returns 404. This time, the URL is correct except for the slug, that is in EN.

image

**Comment by PedroAntunesCosta** [comment]
Maybe we should consider the possibility that your code is correct, but the preview branch feature is not working right in the tracks page. Except maybe in this case it wouldn't return any content in the cards, IDK 🤔

**Comment by PedroAntunesCosta** [comment]
Also, when I navigate back to the home, it goes back to PT and I can't change locales in the home page.

**Comment by julia-rabello** [comment]
The tracks page is hardcoded, so its links are incorrect (not localized). I'll add a commit to fix that.

**Comment by julia-rabello** [comment]
Fixed the tracks page, the home page locale switcher behavior, and the locale-switcher-footer component in the latest commits.

**Review by PedroAntunesCosta — APPROVED** [review]
Amazing!

**Review by PedroAntunesCosta — APPROVED** [review]

**Pull request merged**
